import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity({ name: 'subscriptions' })
export default class Subscription {
  @PrimaryGeneratedColumn()
  id!: number;

  // the endpoint is a unique identifier for the subscription generated by the browser
  // one endpoint per user/device/browser combination
  @Column({ type: 'varchar', length: 255 })
  endpoint!: string;

  @Column({ type: 'varchar' })
  user_id!: string;

  @Column({ type: 'varchar' })
  p256dh!: string;

  @Column({ type: 'varchar' })
  auth!: string;

  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  created_at!: Date;

  @Column({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP',
    onUpdate: 'CURRENT_TIMESTAMP',
  })
  updated_at!: Date;
}
